/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.Random;

public class Buzz {

    private boolean capaceteAberto = false;
    private boolean asaAberta = false;
    String[] frasesBuzz = {"Isto não é voar. Isto é cair, com estilo!", "Ao infinito e além!", "Deus não é aquilo que vai no infinito e no além. O nome disso é Buzz Lightyear. \n Deus é outra coisa.", "Nunca duvidei de mim mesmo, Comandante, e não vou começar agora!", "Comando estelar, pronto para voar!"};

    public boolean isCapaceteAberto(){
        return capaceteAberto;
    }


    public boolean capaceteRetratil(){
        capaceteAberto =  !capaceteAberto;
        return capaceteAberto;
    }

    public String frasesBuzz(String[] frases){
        Random numeroAleatorio = new Random();
        int indexAleatorio = numeroAleatorio.nextInt(6);
        String fraseEscolhida = frases[indexAleatorio];
        return fraseEscolhida;
    }

    public String lazers(){
        return "Disparando Lazers!";
    }

    public String bracoArticulado(){
        return "Golpeando!";
    }

    public boolean asaAberta(){
        asaAberta = !asaAberta;
        return asaAberta;
    }
}
